import { GoogleGenAI, GenerateContentResponse, Content, Part } from "@google/genai";
import { GroundingSource } from "../types.ts";

const SYSTEM_INSTRUCTION = `
You are an elite Professor of Fetal Medicine and Gynecology at King's College London, strictly adhering to ISUOG, FMF, IOTA, MUSA, and IETA guidelines. Your task is to synthesize extracted ultrasound data into a highly academic, authoritative, and concise medical report.

CORE OPERATIONAL DIRECTIVE:
- You are an expert OBGYN AI assistant. 
- If the case status is 'Normal', generate a standard comprehensive normal ultrasound report based on the image/video findings.
- If the case status is 'Abnormal', you MUST focus your analysis specifically on the 'Doctor's Suspicions/Observations'. 
- DO NOT hallucinate or invent diagnoses. Only describe what is visible in the media and correlates with or refutes the doctor's notes based on visual evidence.

CRITICAL TONE & STYLE GUIDELINES:
- Tone: Objective, academic, and highly professional. Use passive voice (e.g., "The fetal anatomy was visualized and appears unremarkable" instead of "I saw the anatomy").
- Brevity: Avoid conversational filler. Be uncompromisingly precise.
- Terminology: Use elite clinical phrasing (e.g., "concordant with dates," "hemodynamics are within normal limits," "suboptimal visualization secondary to [reason]").
- Null Values: If a parameter is not explicitly measured or visible, state "Not visualized" or "Not assessed." NEVER invent, infer, or hallucinate data.

MANDATORY REPORT STRUCTURE:

[Header]
OGX AI CLINICAL REPORT

1. PATIENT DEMOGRAPHICS & CLINICAL CONTEXT
- Age / GA / LMP / EDD: [Extract strictly from images]
- Indication: [Reason for scan]

2. BIOMETRY & FETAL/PELVIC MEASUREMENTS
- Present all extracted numerical data (CRL, BPD, HC, AC, FL, EFW, or Gynecological dimensions) in a clean, structured format. 
- State growth percentiles ONLY if explicitly visible on the scan.
- For multiples: Clearly delineate Fetus A vs. Fetus B and report inter-twin discordance strictly based on provided numbers.

3. ANATOMICAL SURVEY (Fetal or Gynecological)
- Fetal: Systematically review Head, Face, Spine, Thorax, Heart (4CH, outflow tracts), Abdomen, Kidneys, Bladder, and Extremities.
- Gynecological (IOTA/MUSA/IETA): Systematically describe myometrium, endometrium, and adnexa. 
- ENDOMETRIAL PROTOCOL (Nurture Fertility/GE Guidelines): 
    * Identify Phase: Post-menstrual (thin), Proliferative (Triple-line/Trilaminar), or Luteal (Homogenous/Hyperechogenic).
    * Clinical Correlation: For fertility/receptivity, note if thickness meets the >= 7-8 mm threshold for embryo transfer.
    * Pathology: Specifically look for signs of Adenomyosis (junctional zone), Polyps, Submucosal Fibroids, or IUCD position.
- UTERINE MALFORMATIONS (ESHRE-ESGE Classification):
    * Classify anomalies using 3D coronal plane criteria:
    * Class U0: Normal uterus.
    * Class U1: Dysmorphic (U1a: T-shaped, U1b: Infantilis).
    * Class U2: Septate (U2a: Partial, U2b: Complete).
    * Class U3: Bicorporeal (U3a: Partial, U3b: Complete, U3c: Bicorporeal septate).
    * Class U4: Hemi-uterus (U4a: with functional rudimentary cavity, U4b: without).
- IMPORTANT: If images do not show a specific organ, strictly write "Not assessed in the provided views."

4. HEMODYNAMICS & DOPPLER
- Report PI, RI, and PSV for Uterine, Umbilical, MCA, or Adnexal vessels only if numerical calipers are visible. 

5. CLINICAL IMPRESSION
- Provide a singular, authoritative synthesis. 
- Example (Obstetric): "Single live intrauterine pregnancy with biometry concordant with X weeks of gestation. Normal amniotic fluid volume and unremarkable umbilical artery Doppler hemodynamics."
- Example (Gynecology): "Right adnexal unilocular-solid cyst with IOTA features suggestive of a benign etiology."

6. RECOMMENDATIONS
- Standardized academic recommendations (e.g., "Routine structural anomaly scan at 20 weeks," "Clinical correlation and follow-up scan in 14 days," or "Referral to fetal medicine unit").

ANTI-HALLUCINATION & FORMATTING RULES:
- DO NOT diagnose multiple gestations unless multiple distinct fetal poles/heartbeats are explicitly measured.
- Ensure the final output contains EXACTLY ONE signature at the very bottom, formatted precisely as:
"Generated by OGX AI - www.obgynx.com"
`;

function extractGroundingSources(response: GenerateContentResponse): GroundingSource[] {
  const sources: GroundingSource[] = [];
  try {
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks;
    if (chunks) {
      chunks.forEach((chunk: any) => {
        if (chunk.web && chunk.web.uri) {
          sources.push({ title: chunk.web.title || "Clinical Reference", uri: chunk.web.uri });
        }
      });
    }
  } catch (e) {
    console.warn("Grounding extraction failed", e);
  }
  return Array.from(new Map(sources.map(item => [item.uri, item])).values());
}

function getAIClient() {
  // Always prefer the platform-provided GEMINI_API_KEY
  let key = process.env.GEMINI_API_KEY || import.meta.env.VITE_GEMINI_API_KEY;
  
  // If the user accidentally set the value to the literal string "GEMINI_API_KEY", fallback to VITE_GEMINI_API_KEY
  if (key === "GEMINI_API_KEY") {
    key = import.meta.env.VITE_GEMINI_API_KEY;
  }
  
  if (!key || key === "undefined") {
    throw new Error("API key is missing. Please ensure the environment is correctly configured.");
  }
  
  if (key.startsWith("AQ.") || key.startsWith("1:")) {
    throw new Error("INVALID_KEY_FORMAT: You have pasted a Firebase key instead of a Gemini API key in the Settings. Please open Settings (gear icon), DELETE the GEMINI_API_KEY variable, and try again.");
  }

  if (key === "AI Studio Free Tier" || key.includes("Free Tier")) {
    throw new Error("INVALID_KEY_VALUE: The system received the literal text 'AI Studio Free Tier'. Please go to https://aistudio.google.com/app/apikey, create a real API key (starts with AIza...), and paste it into the Value field for VITE_GEMINI_API_KEY. Then click 'Apply changes'.");
  }

  if (key === "GEMINI_API_KEY") {
    throw new Error("INVALID_KEY_VALUE: The system is still receiving the literal text 'GEMINI_API_KEY'. Please create a NEW secret named VITE_GEMINI_API_KEY and paste your AIza... key as its value, then click 'Apply changes'.");
  }

  // If it's still failing, let's show the first 10 characters so we know what's being sent
  try {
    return new GoogleGenAI({ apiKey: key });
  } catch (e: any) {
    throw new Error(`Failed to initialize AI Client. Key starts with: "${key.substring(0, 10)}...". Error: ${e.message}`);
  }
}

export async function analyzeUltrasoundVideo(
  videoBase64: string,
  mimeType: string,
  clinicalContext: string,
  patientName: string,
  maternalAge: number,
  scanStatus: 'normal' | 'abnormal' = 'normal',
  doctorNotes: string = ''
): Promise<{ reportMarkdown: string; groundingSources: GroundingSource[] }> {
  const ai = getAIClient();
  const model = 'gemini-3.1-pro-preview';
  
  const prompt = `Ultrasound Video Consultation (Academic Protocol - King's College London):
  Patient: ${patientName}
  Age: ${maternalAge}
  Indication: ${clinicalContext || 'Routine Assessment'}
  Case Status: ${scanStatus.toUpperCase()}
  ${scanStatus === 'abnormal' ? `Doctor's Suspicions/Observations: ${doctorNotes}` : ''}
  
  TASK:
  1. Synthesize the attached ultrasound cine loop (video) into a highly academic medical report.
  2. If status is 'NORMAL', provide a comprehensive normal assessment.
  3. If status is 'ABNORMAL', focus specifically on the findings mentioned in 'Doctor's Suspicions'.
  4. Adhere strictly to the MANDATORY REPORT STRUCTURE and clinical guidelines (ISUOG, FMF, IOTA, MUSA, IETA) defined in your system instructions.
  5. Maintain an objective, professional tone using passive voice.
  6. Ensure all biometry and hemodynamic data are extracted with uncompromising precision.`;

  const videoPart: Part = {
    inlineData: { mimeType, data: videoBase64 }
  };

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: model,
      contents: { parts: [videoPart, { text: prompt }] },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0
      },
    });

    if (!response.text) throw new Error("Video synthesis failed. No diagnostic data returned.");
    
    return {
      reportMarkdown: response.text,
      groundingSources: extractGroundingSources(response)
    };
  } catch (e: any) {
    throw new Error(`Video API Error: ${e.message}`);
  }
}

export async function analyzeUltrasound(
  images64: string[], 
  clinicalContext: string,
  patientName: string,
  maternalAge: number,
  previousScanReport?: string,
  scanStatus: 'normal' | 'abnormal' = 'normal',
  doctorNotes: string = ''
): Promise<{ reportMarkdown: string; groundingSources: GroundingSource[] }> {
  const ai = getAIClient();
  const model = 'gemini-3-flash-preview';
  
  let prompt = `Ultrasound Consultation (Academic Protocol - King's College London):
  Patient: ${patientName}
  Age: ${maternalAge}
  Indication: ${clinicalContext || 'Routine Assessment'}
  Case Status: ${scanStatus.toUpperCase()}
  ${scanStatus === 'abnormal' ? `Doctor's Suspicions/Observations: ${doctorNotes}` : ''}
  
  TASK:
  1. Synthesize the attached ${images64.length} ultrasound frames into a highly academic medical report.
  2. If status is 'NORMAL', provide a comprehensive normal assessment.
  3. If status is 'ABNORMAL', focus specifically on the findings mentioned in 'Doctor's Suspicions'.
  4. Adhere strictly to the MANDATORY REPORT STRUCTURE and clinical guidelines (ISUOG, FMF, IOTA, MUSA, IETA) defined in your system instructions.
  5. Maintain an objective, professional tone using passive voice.
  6. Extract all biometry and Doppler data with uncompromising precision.`;

  if (previousScanReport) {
    prompt += `\n\nPREVIOUS SCAN REPORT FOR COMPARISON:\n${previousScanReport}\n\nIMPORTANT: Compare current findings with the previous scan report above. Highlight any significant changes in biometry, anatomy, or clinical impression.`;
  }

  const imageParts: Part[] = images64.map(base64 => ({
    inlineData: { mimeType: 'image/jpeg', data: base64 }
  }));

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: model,
      contents: { parts: [...imageParts, { text: prompt }] },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0
      },
    });

    if (!response.text) throw new Error("Synthesis failed. No diagnostic data returned.");
    
    return {
      reportMarkdown: response.text,
      groundingSources: extractGroundingSources(response)
    };
  } catch (e: any) {
    const key = import.meta.env.VITE_GEMINI_API_KEY || process.env.GEMINI_API_KEY || "";
    const prefix = key.substring(0, 10);
    throw new Error(`API Error: ${e.message} (Debug: Key starts with "${prefix}...", length: ${key.length})`);
  }
}

export async function refineReport(
  images64: string[], 
  previousReport: string, 
  refinement: string,
  clinicalContext: string,
  patientName: string,
  maternalAge: number,
  scanStatus: 'normal' | 'abnormal' = 'normal',
  doctorNotes: string = ''
): Promise<{ reportMarkdown: string; groundingSources: GroundingSource[] }> {
  const ai = getAIClient();
  const model = 'gemini-3-flash-preview';

  const imageParts: Part[] = images64.map(base64 => ({
    inlineData: { mimeType: 'image/jpeg', data: base64 }
  }));

  const contents: Content[] = [
    {
      role: 'user',
      parts: [...imageParts, { text: `Refinement request for Patient ${patientName}. Case Status: ${scanStatus.toUpperCase()}. ${scanStatus === 'abnormal' ? `Doctor's Suspicions: ${doctorNotes}` : ''}` }]
    },
    { role: 'model', parts: [{ text: previousReport }] },
    { role: 'user', parts: [{ text: refinement }] }
  ];

  const response = await ai.models.generateContent({
    model: model,
    contents: contents,
    config: {
      systemInstruction: SYSTEM_INSTRUCTION,
      temperature: 0
    },
  });

  if (!response.text) throw new Error("Refinement cycle failed.");
  return { reportMarkdown: response.text, groundingSources: extractGroundingSources(response) };
}

export async function extractClinicalData(images64: string[]): Promise<any> {
  const ai = getAIClient();
  const model = 'gemini-3-flash-preview';
  
  const prompt = `You are an expert OB/GYN ultrasound reporting assistant. Analyze the attached ultrasound monitor screenshots carefully.

Tasks:
1. Extract ALL visible text and numbers exactly as shown (patient name, age, date, GA/LMP, machine brand if visible).
2. Extract fetal biometry measurements: BPD, HC, AC, FL, HL, CRL, NT, AFI, etc. Include exact values + units.
3. If Doppler indices visible (UA PI, RI, MCA, CPR, DV), extract them too.
4. Identify any calculated values like EFW, percentile, or IUGR flags if present.
5. Output ONLY in strict JSON format, no extra text.

JSON Structure:
{
  "patient_info": {
    "name": "...",
    "age": "...",
    "ga_weeks": "...",
    "ga_days": "...",
    "edd": "...",
    "date": "...",
    "machine": "..."
  },
  "biometry": {
    "BPD": {"value": "...", "unit": "mm", "percentile": "..."},
    "HC": {"value": "...", "unit": "mm", "percentile": "..."},
    "AC": {"value": "...", "unit": "mm", "percentile": "..."},
    "FL": {"value": "...", "unit": "mm", "percentile": "..."},
    "EFW": {"value": "...", "unit": "g", "percentile": "..."}
  },
  "doppler": {
    "UA_PI": "...",
    "UA_RI": "...",
    "MCA_PI": "..."
  },
  "other_findings": "...",
  "confidence": {"overall": 0-100, "notes": "..."}
}`;

  const imageParts: Part[] = images64.map(base64 => ({
    inlineData: { mimeType: 'image/jpeg', data: base64 }
  }));

  const response = await ai.models.generateContent({
    model: model,
    contents: { parts: [...imageParts, { text: prompt }] },
    config: {
      responseMimeType: "application/json",
      temperature: 0,
    },
  });

  if (!response.text) throw new Error("Data extraction failed.");
  return JSON.parse(response.text);
}
